"version: '0.0'"

services:
  app:
    container_name: app-dev
    image: "app"
    build: 
      context: .
      target: development
    ports:
      - "3000:3000"
    volumes:
      - ./src:/app/src